trigger:
  - main

jobs:
- job: PushToAzureDevOps
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: Git@v2
    inputs:
      repository: 'https://github.com/your-github-username/https://github.com/ErnestoAlfonso/GameStore.git'
      branch: 'main'
      
  - task: AzureDevOpsGit@1
    inputs:
      connectedServiceName: 'your-azure-devops-connection'
      repository: 'https://dev.azure.com/your-azure-devops-org/Prueba1/_git/Prueba1'
      branch: 'main'
      pushChanges: true
      tagSource: 'auto'
