name: Mirror to Azure DevOps

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Mirror to Azure DevOps
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZUREPAT }}
      run: |
        git push Prueba1 main
      shell: bash
